In [ ]:
import joblib
import numpy as np
import pandas as pd

# Chargement du modèle depuis le dossier visible sur ta capture
model = joblib.load('models/rf_model.joblib')

# Définition des 5 entrées attendues (ordre probable de ton entraînement)
columns = ['temperature', 'humidity', 'co2', 'lumiere', 'sol']

# Simulation : T=28°C, Hum=85%, CO2=900, Lum=15000, Sol=40%
data_test = pd.DataFrame([[28.0, 85.0, 900.0, 15000.0, 40.0]], columns=columns)

# Prédiction
prediction = model.predict(data_test)
proba = model.predict_proba(data_test)

print(f"Résultat : {prediction[0]}")
print(f"Confiance : {np.max(proba)*100:.2f}%")

In [2]:
import pandas as pd
df = pd.read_csv('data/sensor_data.csv') # Vérifie le nom exact du fichier dans le dossier data
df.head()

,temperature,humidity,co2,lumiere,sol,timestamp
0,18.600000,72.000000,800.000000,20000.000000,50.000000,2026-03-10T12:56:41.908512
1,19.308217,60.916641,858.631977,0.000000,54.908592,2025-01-01 00:00:00
2,20.461704,67.086330,710.096255,1123.410332,48.358423,2025-01-01 00:05:00
3,19.878998,62.272722,753.461326,0.000000,47.231724,2025-01-01 00:10:00
4,16.389049,70.339329,729.897226,507.564897,61.112105,2025-01-01 00:15:00

In [2]:
import pandas as pd
df = pd.read_csv('data/sensor_data.csv') # Vérifie le nom exact du fichier dans le dossier data
df.head()

,temperature,humidity,co2,lumiere,sol,timestamp
0,18.600000,72.000000,800.000000,20000.000000,50.000000,2026-03-10T12:56:41.908512
1,19.308217,60.916641,858.631977,0.000000,54.908592,2025-01-01 00:00:00
2,20.461704,67.086330,710.096255,1123.410332,48.358423,2025-01-01 00:05:00
3,19.878998,62.272722,753.461326,0.000000,47.231724,2025-01-01 00:10:00
4,16.389049,70.339329,729.897226,507.564897,61.112105,2025-01-01 00:15:00

In [4]:
def compute_risk(row):
    score = 0
    t = row['temperature']
    h = row['humidity']

    if h > 90 and 10 <= t <= 25:
        score += 40
    if h > 85 and 15 <= t <= 20:
        score += 35
    if 40 <= h <= 80 and 20 <= t <= 27:
        score += 25
    if h > 90 and 10 <= t <= 20:
        score += 30
    if h < 65 and t > 25:
        score += 35
    if 20 <= t <= 30:
        score += 15
    if t > 20 and h < 50:
        score += 25
    if 15 <= t <= 25:
        score += 10

    if score >= 60:
        return 2
    elif score >= 30:
        return 1
    return 0

# Ajouter colonne
df['risk_label'] = df.apply(compute_risk, axis=1)

print(df['risk_label'].value_counts())

risk_label
0    428
1    341
2    232
Name: count, dtype: int64

In [5]:
rf_model = joblib.load('rf_model.joblib')

FileNotFoundError: [Errno 2] No such file or directory: 'rf_model.joblib'

In [6]:
X = df[['temperature', 'humidity', 'co2', 'sol']].values

df['prediction'] = rf_model.predict(X)

NameError: name 'rf_model' is not defined